export const StorageKeys = {
  experiencePreferences: '@lulu/experience_preferences_v1',
  onboardingCompleted: '@pet_health_journal/onboarding_completed',
  currentUserId: '@pet_health_journal/current_user_id',
  checkInPreferences: '@pet_health_journal/check_in_preferences',
  checkInReminderTime: '@pet_health_journal/check_in_reminder_time',
  appAppearance: '@pet_health_journal/app_appearance',
  appLanguage: '@pet_health_journal/app_language',
  notificationPermission: '@pet_health_journal/notification_permission',
  petReminderNotificationsEnabled: '@pet_health_journal/pet_reminder_notifications_enabled',
  familyActivityDigestEnabled: '@pet_health_journal/family_activity_digest_enabled',
  expoPushToken: '@pet_health_journal/expo_push_token',
  activePetId: '@pet_health_journal/active_pet_id',
  userProfile: '@pet_health_journal/user_profile',
  lastStoreReviewPromptAt: '@pet_health_journal/last_store_review_prompt_at',
  petSetupGuideDismissed: '@pet_health_journal/pet_setup_guide_dismissed',
  inboxDismissed: '@pet_health_journal/inbox_dismissed',
  familyActivityLastReadAt: '@pet_health_journal/family_activity_last_read_at',
  pendingFamilyJoinCode: '@pet_health_journal/pending_family_join_code',
  userSetupPath: '@pet_health_journal/user_setup_path',
  joinRemindersPromptPending: '@pet_health_journal/join_reminders_prompt_pending',
  joinRemindersPromptDismissed: '@pet_health_journal/join_reminders_prompt_dismissed',
  contextualEducationDismissed: '@pet_health_journal/contextual_education_dismissed',
} as const;

export type StorageKey = (typeof StorageKeys)[keyof typeof StorageKeys];
